version: '3.1'
services:
  ghost:
    image: ghost:latest
    volumes:
      - ./ghost/volume:/var/lib/ghost/content
    ports:
      - '60000:2368'
    restart: always
    environment:
      url: http://localhost:60000
